basket/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.BasketDetail, name='BasketDetail'),
    url(r'^remove/(?P<dish_id>\d+)/$', views.BasketRemove, name='BasketRemove'),
    url(r'^add/(?P<dish_id>\d+)/$', views.BasketAdd, name='BasketAdd'),
]

cafe/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.DishList, name='DishList'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.DishList, name='DishListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.DishDetail, name='DishDetail'),
]

online_cafe/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^basket/', include('basket.urls', namespace='basket')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^payment/', include('pay.urls', namespace='payment')),
    url(r'^promocods/', include('promocods.urls', namespace='promocode')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^', include('cafe.urls', namespace='cafe')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

orders/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [
    url(r'^create/$', views.OrderCreate, name='OrderCreate'),
    url(r'^admin/order/(?P<order_id>\d+)/$', views.AdminOrderDetail, name='AdminOrderDetail'),
    url(r'^admin/order/(?P<order_id>\d+)/pdf/$', views.AdminOrderPDF, name='AdminOrderPDF')

]

pay/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^process/$', views.PaymentProcess, name='process'),
    url(r'^done/$', views.PaymentDone, name='done'),
    url(r'^canceled/$', views.PaymentCanceled, name='canceled')
]

promocods/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^apply', views.PromocodeApply, name='apply')
]\

basket/models.py
from django.db import models

# Create your models here.

basket/forms.py
from django import forms


DISH_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class BasketAddDishForm(forms.Form):
    quantity = forms.TypedChoiceField(choices=DISH_QUANTITY_CHOICES, coerce=int)
    update = forms.BooleanField(required=False, initial=False, widget=forms.HiddenInput)

basket/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from cafe.models import Dish
from .basket import Basket
from .forms import BasketAddDishForm
from promocods.forms import PromocodeApllyForm


@require_POST
def BasketAdd(request, dish_id):
    basket = Basket(request)
    dish = get_object_or_404(Dish, id=dish_id)
    form = BasketAddDishForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        basket.add(dish=dish, quantity=cd['quantity'],
                                  update_quantity=cd['update'])
    return redirect('basket:BasketDetail')


def BasketRemove(request, dish_id):
    basket = Basket(request)
    dish = get_object_or_404(Dish, id=dish_id)
    basket.remove(dish)
    return redirect('basket:BasketDetail')



def BasketDetail(request):
    basket = Basket(request)
    for item in basket:
    	item['update_quantity_form'] = BasketAddDishForm(
    		       initial={'quantity': item['quantity'],
    		                'update': True})
    promocode_apply_form = PromocodeApllyForm()
    return render(request, 'basket/detail.html', {'basket': basket, 'promocode_apply_form': promocode_apply_form})

basket/templates/basket/detail.html
{% extends "cafe/base.html" %}

{% block title %}
  Ваша корзина 
{% endblock %}

{% block content %}
  <center style='color:#800000';><font face='Cursive';><h1>Ваш заказ: </h1></center></font>
  <table class="basket">
    <thead>
      <tr>
        <th>Изображение</th>
        <th>Блюдо</th>
        <th>Количество</th>
        <th>Удалить</th>
        <th>Полная цена</th>
        <th>Цена</th>
      </tr>
    </thead>
    <tbody>
      {% for item in basket %}
        {% with dish=item.dish %}
          <tr>
            <td class="basket-img">
              <a href="{{ dish.get_absolute_url }}">
                <img src="{{ dish.image.url }}" class="img-responsive" />
              </a>
            </td>
            <td>{{ dish.name }}</td>
            <td>
              <form action="{% url "basket:BasketAdd" dish.id %}" method="post" class="add">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                {% csrf_token %}
                <input style='background:#d2b48c; color:#f5deb3'' type="submit" value="Изменить">
              </form>
            </td>
            <td><p><strong><a style='color:#800000' href="{% url "basket:BasketRemove" dish.id %}">Удалить</a></td></strong></p>
            <td class="num">{{ item.price }} руб.</td>
            <td class="num">{{ item.total_price }} руб.</td>
          </tr>
        {% endwith %}

      {% endfor %}
        {% if basket.promocode %}
          <tr class="subtotal">
            <td><p><strong><center>Сумма без скидки:</td></center></strong></p>
            <td colspan="4"></td>
            <td>{{ basket.get_total_price }}</td>
          </tr>
          <tr>
            <td><p><strong><center>
              "{{ basket.promocode.code }}" промокод на ({{ basket.promocode.discount }} % ниже)
            </strong></p></center></td>
            <td colspan="4"></td>
            <td class="num discount">- {{ basket.get_discount|floatformat:"2" }} руб.</td>
          </tr>
        {% endif %}
        <tr class="total">
          <td colspan="4"></td>
          <td><p><center><strong class="num">Итого: {{ basket.get_total_price_after_discount|floatformat:"2" }} руб.</center></td></strong></p>
        </tr>
    </tbody>
  </table>

  <center><p style='background:#d2b48c; color:#800000'>Применить промокод</p>
  <form action = "{% url 'promocode:apply' %}" method="post" class="add">
    {% csrf_token %}
    {{promocode_apply_form }}
    <input style='background:#d2b48c; color:#f5deb3' type="submit" value="Применить">
  </form></center>

  <p class="text-center">
    <a style='background:#d2b48c; color:#800000' href="{% url "cafe:DishList"%}" class="btn">Продолжить выбор блюд</a>
    <a style='background:#d2b48c; color:#800000' href="{% url "orders:OrderCreate" %}" class="btn">Оформить заказ</a>
  </p>
{% endblock %}