basket/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.BasketDetail, name='BasketDetail'),
    url(r'^remove/(?P<dish_id>\d+)/$', views.BasketRemove, name='BasketRemove'),
    url(r'^add/(?P<dish_id>\d+)/$', views.BasketAdd, name='BasketAdd'),
]

cafe/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.DishList, name='DishList'),
    url(r'^(?P<category_slug>[-\w]+)/$', views.DishList, name='DishListByCategory'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$', views.DishDetail, name='DishDetail'),
]

online_cafe/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^basket/', include('basket.urls', namespace='basket')),
    url(r'^order/', include('orders.urls', namespace='orders')),
    url(r'^payment/', include('pay.urls', namespace='payment')),
    url(r'^promocods/', include('promocods.urls', namespace='promocode')),
    url(r'^paypal/', include('paypal.standard.ipn.urls')),
    url(r'^', include('cafe.urls', namespace='cafe')),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) 

pay/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^process/$', views.PaymentProcess, name='process'),
    url(r'^done/$', views.PaymentDone, name='done'),
    url(r'^canceled/$', views.PaymentCanceled, name='canceled')
]

cafe/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Category(models.Model):
    name = models.CharField(max_length=200, db_index=True)
    slug = models.SlugField(max_length=200, db_index=True, unique=True)

    class Meta:
        ordering = ['name']
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории блюд'

    def get_absolute_url(self):
        return reverse('cafe:DishListByCategory', args=[self.slug])

    def __str__(self):
        return self.name


class Dish(models.Model):
    category = models.ForeignKey(Category, related_name='foods', verbose_name="Категория")
    name = models.CharField(max_length=200, db_index=True, verbose_name="Название")
    slug = models.SlugField(max_length=200, db_index=True)
    image = models.ImageField(upload_to='foods/', blank=True, verbose_name="Изображение блюда")
    description = models.TextField(blank=True, verbose_name="Описание")
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name="Цена")
    available = models.BooleanField(default=True, verbose_name="Доступно")
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_absolute_url(self):
          return reverse('cafe:DishDetail', args=[self.id, self.slug])


    class Meta:
        ordering = ['name']
        index_together = [
            ['id', 'slug']
        ]

    def __str__(self):
        return self.name

cafe/views.py
from django.shortcuts import render, get_object_or_404, render_to_response
from .models import *
from basket.forms import BasketAddDishForm


def DishList(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    dishs = Dish.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        dishs = dishs.filter(category=category)
    return render(request, 'cafe/dish/list.html', {
        'category': category,
        'categories': categories,
        'dishs': dishs})


def DishDetail(request, id, slug):
    dish = get_object_or_404(Dish, id=id, slug=slug, available=True)
    basket_dish_form = BasketAddDishForm()
    return render(request,'cafe/dish/detail.html',
                    {'dish': dish,
                    'basket_dish_form': basket_dish_form})

cafe/templates/cafe/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{% block title %}{% endblock %}</title>
  <link rel="stylesheet" href="{% static "bootstrap.min.css" %}">
  <link rel="stylesheet" href="{% static "style.css" %}">
</head>
<body style='background:#fffacd'>
  <center><p><img src="http://static1.squarespace.com/static/54878917e4b09cb7ec706a8d/t/54f4dd51e4b0447d468ecd6e/1495900043058/?format=750w" alt="BonAppetit"></p>
</center>
  <section id="header">

    <div class="top-bl">
      <div class="container">
       <font face='Cursive';><div class="basket">
    {% with total_items=basket|length %}
        {% if basket|length > 0 %}
            Ваш заказ:
            <a  style='color:#800000'; href="{% url "basket:BasketDetail" %}">
                {{ total_items }} тов. {{ basket.get_total_price }} руб.
            </a>
         {% else %}
              
        {% endif %}
    {% endwith %}
</div></font>
    </div>
  </section><center><div id="cp_widget_5c4ed70a-4b19-4b2f-b363-7693758bbfb9">...</div><script type="text/javascript">
var cpo = []; cpo["_object"] ="cp_widget_5c4ed70a-4b19-4b2f-b363-7693758bbfb9"; cpo["_fid"] = "AwBAK9tsmrwd";
var _cpmp = _cpmp || []; _cpmp.push(cpo);
(function() { var cp = document.createElement("script"); cp.type = "text/javascript";
cp.async = true; cp.src = "//www.cincopa.com/media-platform/runtime/libasync.js";
var c = document.getElementsByTagName("script")[0];
c.parentNode.insertBefore(cp, c); })(); </script><noscript><span>Online cafe</span><span>Online cafe music </span></noscript></center>
  <section id="content row" class="container">
    {% block content %}{% endblock %}
  </section>
</body>
</html>